baseURL = 'https://lib.ugent.be'
languageCode = 'en-us'
title = 'Ghent University Library'

[module]
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Libraries'
    pageRef = '/libraries'
    weight = 20

  [[menus.main]]
    name = 'Databases'
    pageRef = '/databases'
    weight = 30

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40
